name = "pdf-create"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]



[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'byzantini-bucket'

